name: dice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - img/dice1.png
    - img/dice2.png
    - img/dice3.png
    - img/dice4.png
    - img/dice5.png
    - img/dice6.png

